django_twitter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from twitter import views as twitter_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", twitter_views.TweetListView.as_view(), name="home"),
    path("explore/", twitter_views.TweetListView.as_view(), name="all-tweets"),
    path("register/", user_views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path("profile/", user_views.private_profile, name="private-profile"),
    path(
        "tweet/<int:pk>/", twitter_views.TweetDetailView.as_view(), name="tweet-detail"
    ),
    path(
        "<str:username>/",
        twitter_views.UserTweetListView.as_view(),
        name="public-profile",
    ),
    path(
        "hashtag/<str:hashtag>/",
        twitter_views.HashtagListView.as_view(),
        name="hashtag",
    ),
    path(
        "delete/<int:pk>/", twitter_views.TweetDeleteView.as_view(), name="tweet-delete"
    ),
    path("<str:username>/follow/", user_views.follow_user, name="follow-user"),
    path("<str:username>/unfollow/", user_views.unfollow_user, name="unfollow-user"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter/urls.py
from django.urls import path
from . import views

urlpatterns = []

twitter/models.py
from django.db import models
from django.contrib.auth.models import User


class Tweet(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE
    )  # If the 'many' part (User) is deleted, the waterfall of destruction cascades down and washes away the 'one' (Tweets)  too.
    message = models.CharField(max_length=280)
    date_created = models.DateTimeField(auto_now=True)

twitter/forms.py
from django.forms import ModelForm, Textarea
from .models import Tweet


class TweetForm(ModelForm):
    class Meta:
        model = Tweet
        fields = ["message"]
        widgets = {
            "message": Textarea(
                attrs={
                    "class": "textarea is-info has-fixed-size",
                    "rows": "2",
                    "placeholder": "What's happening?",
                }
            ),
        }

twitter/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.http import HttpResponse
from django.urls import reverse
from django.views.generic import ListView, DetailView, DeleteView
from .models import Tweet
from .forms import TweetForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.utils.safestring import mark_safe
from django.db.models import Q

# Create your views here.
class TweetListView(ListView):  # Homepage
    model = Tweet
    template_name = "twitter/home.html"
    context_object_name = "tweets"
    ordering = "-date_created"

    def get(self, request, *args, **kwargs):
        """If logged in but doesn't follow anyone, suggest 'Explore'"""
        if not request.user.is_authenticated:
            return super().get(request, *args, **kwargs)

        follows = request.user.profile.follows.count()
        explore_url = reverse("all-tweets")
        if follows == 0:
            messages.add_message(
                request,
                messages.INFO,
                mark_safe(
                    f"""Find some people to follow: <strong><a href="{explore_url}">Explore</a></strong>!"""
                ),
            )
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = TweetForm()
        return context

    def post(self, request):
        form = TweetForm(request.POST)
        form.instance.author = request.user
        if form.is_valid():
            form.save()
        return redirect("home")

    def get_queryset(self):
        """If auth'd, only show tweets from authors the user follows.
        If not auth'd or a user has gone to 'explore', show all tweets."""
        if self.request.user.is_authenticated and self.request.path_info != reverse(
            "all-tweets"
        ):
            print(self.request.path_info)
            followees = self.request.user.profile.follows.all()
            q_followees = Q(author__in=followees)
            q_user = Q(author=self.request.user)
            queryset = Tweet.objects.filter(q_followees | q_user).all()
        else:
            queryset = super().get_queryset()
        return queryset


class TweetDetailView(DetailView):
    model = Tweet
    context_object_name = "tweet"


class TweetDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Tweet
    success_url = "/"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        tweet = self.get_object()
        if self.request.user == tweet.author:
            return True
        return False

    def delete(self, request, *args, **kwargs):
        messages.add_message(request, messages.SUCCESS, "Tweet deleted.")
        return super().delete(request, *args, **kwargs)


class UserTweetListView(ListView):  # Public Profile
    model = Tweet
    template_name = "twitter/public_profile.html"
    context_object_name = "tweets"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        author = get_object_or_404(User, username=self.kwargs.get("username"))

        context["author"] = author
        context["user"] = user
        context["author_follows_count"] = author.profile.follows.count()
        context["author_followers_count"] = User.objects.filter(
            followers__user=user
        ).count()
        return context

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get("username"))
        return Tweet.objects.filter(author=user).order_by("-date_created")


class HashtagListView(ListView):
    model = Tweet
    template_name = "twitter/hashtag.html"
    context_object_name = "tweets"

    def get_queryset(self):
        return get_list_or_404(
            Tweet, message__icontains=f"#{self.kwargs.get('hashtag')}"
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["hashtag"] = self.kwargs.get("hashtag")
        return context

twitter/templates/twitter/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Twitter Clone</title>
    <link rel="stylesheet" href="{% static 'twitter/base.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/dd9c3a3d41.js" crossorigin="anonymous"></script>
    
</head>
<body>

    <!-- Navbar -->
  <div id="wrapper">
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="{% url 'home' %}">
        <i class="fab fa-twitter fa-2x"></i>
        <h1 class="title m-3">Twitter</h1>
      </a>
  
      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
  
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item" href="{% url 'home' %}">Home</a>
        {% if user.is_authenticated %}
          <a class="navbar-item" href="{% url 'public-profile' user.username %}">Profile</a>
          <a class="navbar-item" href="{% url 'all-tweets' %}">Explore</a>
        {% endif %}
      </div>
  
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            {% if user.is_authenticated %}
              <a class="button is-danger is-light" href="{% url 'logout' %}">Log Out</a>
              <a class="button is-info is-light" href="{% url 'private-profile' %}"><strong>{{ user.username }}</strong></a>
            {% else %}
              <a class="button is-info" href="{% url 'register' %}"><strong>Sign up</strong></a>
              <a class="button is-light" href="{% url 'login' %}">Log in</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </nav>
  <!-- MESSAGES -->
  <div class="columns">
    <div class="column"></div>
    <div class="column">
      {% if messages %}
        {% for message in messages %}
        <article class="message is-{{ message.tags }}">
          <div class="message-body">
            {{ message }}
          </div>
        </article>
        {% endfor %}
      {% endif %}
    </div>
    <div class="column"></div>
  </div>

    <!-- CONTENT -->

    {% block content %}
    {% endblock %}

  </div>
    <!-- FOOTER -->
    <footer class="footer">
      <div class="content has-text-centered">
        <p>
          <strong>Twitter Clone</strong> by <a href="https://github.com/Ben-Hampson">Ben Hampson</a> using <a href="https://www.djangoproject.com/" target="_blank">Django</a> and <a href="https://bulma.io/" target="_blank">Bulma</a>.
        </p>
      </div>
    </footer>

</body>
</html>

twitter/templates/twitter/hashtag.html
{% extends "twitter/base.html" %}
{% block content %}

{% load bulma_tags %}
{% load hashtags %}

<div class="columns">
    <div class="column">
    </div>
    <div class="column is-5">        
        <span class="is-size-3 has-text-weight-bold">#{{ hashtag }}</span>
        
        <!-- TWEET STREAM -->
        {% include "twitter/tweet_list.html" %}
        
    </div>
    <div class="column">
    </div>
</div>
    
{% endblock content %}

twitter/templates/twitter/home.html
{% extends "twitter/base.html" %}
{% block content %}

{% load bulma_tags %}
{% load hashtags %}

<div class="columns">
    <div class="column">
    </div>
    <div class="column is-5">
        <!-- TWEET BOX-->
        {% if user.is_authenticated %}
            <form method="POST">
                {% csrf_token %}
                {{ form.message }}
                <button class="button is-info m-4" type="submit"><strong>Tweet</strong></button>
            </form>
        {% endif %}

        <!-- TWEET STREAM -->
        {% include "twitter/tweet_list.html" %}
        
    </div>
    <div class="column">
    </div>
</div>
    
{% endblock content %}

twitter/templates/twitter/public_profile.html
{% extends "twitter/base.html" %}
{% block content %}

{% load bulma_tags %}
{% load hashtags %}

<div class="columns">
    <div class="column">
    </div>
    <div class="column is-5">        
        <!-- PROFILE CARD -->
        <div class="card mb-4">
            <div class="card-content">
                <figure class="image is-128x128">
                    <img class="is-128x128 is-rounded" src="{{ author.profile.image.url }}">
                </figure>
                <div class="level">
                    <div class="level-left">
                        <div class="level-item">
                            <p class="title">{{ author.profile.display_name }}</p>
                        </div>
                    </div>
                    <div class="level-right">
                        <!-- FOLLOW BUTTON -->
                        <div class="level-item">
                            {% if user.is_authenticated and user != author %}
                                {% if author not in user.profile.follows.all %}
                                    <a href="{% url 'follow-user' author.username %}"><button class="button is-info is-small"><strong>Follow</strong></button></a>
                                {% else %}
                                    <a href="{% url 'unfollow-user' author.username %}"><button class="button is-info is-small"><strong>Unfollow</strong></button></a>
                                {% endif %}
                            {% endif %}
                            {% if user.is_authenticated and user == author %}
                                <a href="{% url 'private-profile' %}"><button class="button is-info is-small"><strong>Edit Profile</strong></button></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <p class="mt-2">@{{ author.username }}</p>
                <p class="mt-2">{{ author.profile.bio }}</p>
                <p class="mt-2">
                    {% if author.profile.location %}
                        <span class="icon"><i class="fas fa-map-marker-alt"></i></span>{{ author.profile.location }} 
                    {% endif %}
                    {% if author.profile.website %}
                    <span class="icon ml-2"><i class="fas fa-link"></i></span>{{ author.profile.website | urlize }} 
                    {% endif %}
                    <span class="icon ml-2"><i class="fas fa-calendar-alt"></i></span>Joined {{ author.date_joined | date:"F Y" }}
                </p>
                <p class="mt-2"><strong>{{ author_follows_count }}</strong> Following   <strong>{{ author_followers_count }}</strong> Followers</p>
            </div>
        </div>


        
        <!-- TWEET STREAM -->
        {% include "twitter/tweet_list.html" %}
        
    </div>
    <div class="column">
    </div>
</div>
    
{% endblock content %}

twitter/templates/twitter/tweet_confirm_delete.html
{% extends "twitter/base.html" %}
{% block content %}
    <div class="columns">
        <div class="column">
        </div>
        <div class="column is-5">
            <h2 class="title">Delete Tweet</h2>
            <p>Are you sure you want to delete the tweet, "{{ object.message }}"?</p>
            <br>
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <button class="button is-danger" type="submit">Yes, Delete</button>
                    <a class="button" href="{% url 'tweet-detail' object.id %}">Cancel</a>
                </div>
            </form>
        </div>
        <div class="column">
        </div>
    </div>
{% endblock content %}

twitter/templates/twitter/tweet_detail.html
{% extends "twitter/base.html" %}
{% block content %}

{% load hashtags %}

<div class="columns">
    <div class="column">
    </div>
    <div class="column is-5">
        {% if messages %}
            {% for message in messages %}
                <div>{{ message }}</div>
            {% endfor %}
        {% endif %}
        
        <article class="media">
            <figure class="media-left">
            <p class="image is-128x128">
                <img src="{{ tweet.author.profile.image.url }}">
            </p>
            </figure>
            <div class="media-content">
            <div class="content">
                <p>
                    <a href="{% url 'public-profile' tweet.author.username %}"><strong>{{ tweet.author.username }}</strong></a> 
                    <small>@{{ tweet.author.username }}</small> <small>{{ tweet.date_created }}</small>
                <br>
                    {{ tweet.message | hashtags | safe }}
                </p>
            </div>
            <nav class="level is-mobile">
                <div class="level-left">
                <a class="level-item">
                    <span class="icon is-small"><i class="fas fa-reply"></i></span>
                </a>
                <a class="level-item">
                    <span class="icon is-small"><i class="fas fa-retweet"></i></span>
                </a>
                <a class="level-item">
                    <span class="icon is-small"><i class="fas fa-heart"></i></span>
                </a>
                </div>
            </nav>
            </div>
            <div class="media-right">
            <button class="delete"></button>
            </div>
        </article>
        
    </div>
    <div class="column">
    </div>
</div>
    
{% endblock content %}

twitter/templates/twitter/tweet_list.html
{% block content %}

{% load bulma_tags %}
{% load hashtags %}
    <!-- TWEET STREAM -->
    {% for tweet in tweets %}
        <article class="media">
            <figure class="media-left">
            <p class="image is-64x64">
                <a href="{% url 'public-profile' tweet.author.username %}"><img class="is-64x64 is-rounded" src="{{ tweet.author.profile.image.url }}"></a>
            </p>
            </figure>
            <div class="media-content">
            <div class="content">
                <p>
                    <a href="{% url 'public-profile' tweet.author.username %}">
                    <strong>{{ tweet.author.profile.display_name }}</strong></a>
                    <small class="has-text-grey">@{{ tweet.author.username }}</small> <small class="has-text-grey">{{ tweet.date_created }}</small>
                <br>
                    {{ tweet.message | hashtags | safe }}
                </p>
            </div>
            <nav class="level is-mobile">
                <div class="level-left">
                <a class="level-item">
                    <span class="icon is-small"><i class="fas fa-reply"></i></span>
                </a>
                <a class="level-item">
                    <span class="icon is-small"><i class="fas fa-retweet"></i></span>
                </a>
                <a class="level-item">
                    <span class="icon is-small"><i class="fas fa-heart"></i></span>
                </a>
                </div>
            </nav>
            </div>
            <div class="media-right">
            {% if tweet.author.id == user.id %}
                <a href="{% url 'tweet-delete' tweet.id %}"><button class="delete"></button></a>
            {% endif %}
            </div>
        </article>
    {% endfor %}
{% endblock content %}

twitter/templates/twitter/user_tweets.html
{% extends "twitter/base.html" %}
{% block content %}

{% load bulma_tags %}

<div class="columns">
    <div class="column">
    </div>
    <div class="column">
        <!-- Tweet Stream -->
        {% if messages %}
            {% for message in messages %}
                <div>{{ message }}</div>
            {% endfor %}
        {% endif %}
        
        <span class="is-size-3 has-text-weight-bold">{{ view.kwargs.username }}</span>
        {% for tweet in tweets %}
            <article class="media">
                <figure class="media-left">
                <p class="image is-64x64">
                    <img src="https://bulma.io/images/placeholders/128x128.png">
                </p>
                </figure>
                <div class="media-content">
                <div class="content">
                    <p>
                        <a href="{% url 'public-profile' tweet.author.username %}"><strong>{{ tweet.author.username }}</strong></a> 
                        <small>@{{ tweet.author.username }}</small> <small>{{ tweet.date_created }}</small>
                    <br>
                        {{ tweet.message }}
                    </p>
                </div>
                <nav class="level is-mobile">
                    <div class="level-left">
                    <a class="level-item">
                        <span class="icon is-small"><i class="fas fa-reply"></i></span>
                    </a>
                    <a class="level-item">
                        <span class="icon is-small"><i class="fas fa-retweet"></i></span>
                    </a>
                    <a class="level-item">
                        <span class="icon is-small"><i class="fas fa-heart"></i></span>
                    </a>
                    </div>
                </nav>
                </div>
                <div class="media-right">
                <button class="delete"></button>
                </div>
            </article>
        {% endfor %}
        
    </div>
    <div class="column">
    </div>
</div>
    
{% endblock content %}